use clap::{App, Arg};


fn main() {
    let matches = App::new("tableau-monitoring-execd")
        .version("0.1.0")
        .author("Tamas Foldi <tfoldi@starschema.com>")
        .about("telegraf execd for getting Tableau Cluster status using TSM API and serverinfo.xml")
        .arg(  Arg::new("tsm_user")
            .short('u')
            .long("tsm_user")
            .value_name("USERNAME")
            .about("Username for TSM Authentication")
            .env("TME_TSM_USER")
            .required_if_eq_any(&[("checks", "all"),("checks","tsm")])
            .takes_value(true)
        )
        .arg(  Arg::new("tsm_password")
            .short('p')
            .long("tsm_password")
            .value_name("PASSWORD")
            .about("PASSWORD for TSM Authentication")
            .env("TME_TSM_PASSWORD")
            .required_if_eq_any(&[("checks", "all"),("checks","tsm")])
            .takes_value(true)
        )
        .arg(  Arg::new("tsm_hostname")
            .short('h')
            .long("tsm_hostname")
            .value_name("BASEURL")
            .about("Tableau Server TSM's base url")
            .env("TME_TSM_HOSTNAME")
            .default_value("https://localhost:8850/")
            .takes_value(true)
        )
        .arg(  Arg::new("systeminfo_hostname")
            .short('s')
            .long("si_hostname")
            .value_name("BASEURL")
            .about("Tableau Server's systeminfo web server base URL")
            .env("TME_SI_HOSTNAME")
            .default_value("https://localhost/")
            .takes_value(true)
        )
        .arg(  Arg::new("checks")
            .short('c')
            .long("checks")
            .value_name("CHECKS")
            .about("Username for TSM Authentication")
            .env("TME_CHECKS")
            .takes_value(true)
            .default_value("all")
            .possible_values(&["all", "tsm", "systeminfo"])
        )
        .get_matches();

    tableau_monitoring_execd::run(&matches);
}
